import { VERSION } from "./version.mjs";

export const CAPABILITIES = {
  name: "SISSO-Sage",
  version: VERSION,
  purpose: "Transform SISSO results into compact, auditable evidence that an AI can query before recommending models.",
  commands: {
    inspect: "Validate a SISSO run and return its manifest.",
    leakage: "Check whether held-out rows are genuinely unseen before trusting hold-out metrics.",
    models: "List compact model summaries with filtering and sorting; reports truncation explicitly.",
    model: "Return the full evidence record for one ranked model.",
    compare: "Return aligned evidence records for selected model ranks.",
    pareto: "Return layered Pareto evidence over prediction and generalization gap, with an explicit in-sample fallback.",
    select: "Create an objective-evidence shortlist for subsequent semantic review.",
    bundle: "Write the complete AI-readable analysis bundle.",
    "metadata-template": "Create a feature-provenance template for the run.",
    "feature-doc": "Write a reviewable Markdown feature dictionary and flag unresolved names.",
    "feature-context": "Find exact references to one feature in the supplied extraction source tree.",
  },
  mcpTools: {
    get_capabilities: "Discover the MCP workflow and decision policy.",
    inspect_run: "Validate a run before analysis.",
    check_leakage: "Verify hold-out independence (identical rows, shared structure ids, shared compositions).",
    list_models: "Query a sortable model list; returned/limit/truncated make a partial list explicit.",
    get_model: "Retrieve the full evidence record for one rank.",
    compare_models: "Compare two to ten finalist ranks.",
    pareto_frontier: "Query prediction/gap Pareto layers.",
    select_candidates: "Create a near-optimal objective-evidence candidate shortlist.",
    feature_context: "Trace one exact primitive feature into extraction sources.",
  },
  dictionaryColumns: {
    featureDictionary: ["feature", "note", "unit", "group", "source"],
    renameMap: ["old", "new"],
  },
  decisionPolicy: [
    "Use deterministic metrics and validation results as evidence.",
    "Check hold-out independence before quoting any hold-out metric as generalisation.",
    "Do not calculate or rank by a scalar interpretability or elegance score.",
    "Prefer a shortlist over a single winner.",
    "Require human review of provenance, units, constraints, and extrapolation risks.",
    "Mark ambiguous feature meanings as unresolved instead of inferring them from names alone.",
    "Treat constrained operators as requirements to check; evaluate their arguments over observed data and separately assess the deployment domain.",
    "Keep structural complexity, domain validity, provenance confidence, and semantic interpretation as separate evidence types.",
    "Coefficient differences between MT-SISSO tasks are the method's intended output, not a defect.",
  ],
};
